title: UCL Computer Science project supervision
tagline: A Jekyll theme
description: CS Undergraduate project supervision.
url: 'https://nicholsons.github.io'
baseurl: /about/
paginate: 5
permalink: pretty
author:
  name: Sarah Sanders
  github_username: nicholsons
  email: sarah.sanders@ucl.ac.uk
markdown: GFM
plugins:
  - jekyll-paginate
version: 1.1.0
google_analytics_id: null
