# Welcome to Jekyll!
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# theme: jekyll-theme-so-simple
remote_theme: "mmistakes/so-simple-theme@3.2.0"
skin: "/assets/css/skins/default.css"
locale: en-UK
title: "Sarah Sanders, UCL Computer Science"
description: "Undergraduate project supervision."
url: "https://nicholsons.github.io"
#logo: "/images/so-simple-site-logo-2.png"
baseurl: /about/
date_format: "%B %-d, %Y"
read_time: false
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"

# Liquid
liquid:
  error_mode: strict

# Build settings
markdown: GFM
plugins:
  - jekyll-remote-theme 

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Search
#search_full_content: false

plugins:
  - jekyll-paginate
  - jekyll-redirect-from

# Front Matter Defaults
defaults:
  # Post defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comments: false
      share: false

# Site Author
author:
  name: Sarah Sanders
  picture: /images/sarah.png
  email: sarah_shires@hotmail.com

# Footer Links
footer_links:
  - title: GitHub
    url: https://github.com/nicholsons
    icon: fab fa-github-square
