remote_theme: pages-themes/architect@v0.2.0
show-downloads: false
title: Sarah Sanders, UCl Computer Science
description: CS undergraduate project supervision.
url: "https://nicholsons.github.io"
baseurl: /about/

defaults:
  - scope:
      path: "assets/images"
    values:
      image: true

date_format: "%-d %B, %Y"

# Build settings
markdown: GFM
plugins:
  - jekyll-remote-theme 
